def raise_exception():
    2 + '2'
